2022-04-06 00:26:14,364 INFO    MainThread:31199 [wandb_setup.py:_flush():75] Loading settings from /home/ltorres/.config/wandb/settings
2022-04-06 00:26:14,364 INFO    MainThread:31199 [wandb_setup.py:_flush():75] Loading settings from /home/ltorres/leo/tesis/cloud-classification/code/wandb/settings
2022-04-06 00:26:14,364 INFO    MainThread:31199 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-06 00:26:14,364 INFO    MainThread:31199 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-06 00:26:14,364 INFO    MainThread:31199 [wandb_init.py:_log_setup():405] Logging user logs to /home/ltorres/leo/tesis/cloud-classification/code/wandb/run-20220406_002614-20nr5e0b/logs/debug.log
2022-04-06 00:26:14,364 INFO    MainThread:31199 [wandb_init.py:_log_setup():406] Logging internal logs to /home/ltorres/leo/tesis/cloud-classification/code/wandb/run-20220406_002614-20nr5e0b/logs/debug-internal.log
2022-04-06 00:26:14,364 INFO    MainThread:31199 [wandb_init.py:_jupyter_setup():355] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fa4b4569760>
2022-04-06 00:26:14,364 INFO    MainThread:31199 [wandb_init.py:init():439] calling init triggers
2022-04-06 00:26:14,364 INFO    MainThread:31199 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0003, 'architecture': 'GATConvGNN', 'loss': 'LogeLoss', 'optim': 'SGD', 'dataset': 'GCD', 'builder': 'Pearson correlation', 'epochs': 30}
2022-04-06 00:26:14,364 INFO    MainThread:31199 [wandb_init.py:init():492] starting backend
2022-04-06 00:26:14,364 INFO    MainThread:31199 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-06 00:26:14,399 INFO    MainThread:31199 [backend.py:ensure_launched():219] starting backend process...
2022-04-06 00:26:14,429 INFO    MainThread:31199 [backend.py:ensure_launched():224] started backend process with pid: 31266
2022-04-06 00:26:14,431 INFO    MainThread:31199 [wandb_init.py:init():501] backend started and connected
2022-04-06 00:26:14,447 INFO    MainThread:31199 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-04-06 00:26:14,448 INFO    MainThread:31199 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-04-06 00:26:14,448 INFO    MainThread:31199 [wandb_init.py:init():565] updated telemetry
2022-04-06 00:26:14,530 INFO    MainThread:31199 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-04-06 00:26:15,330 INFO    MainThread:31199 [wandb_run.py:_on_init():1759] communicating current version
2022-04-06 00:26:15,414 INFO    MainThread:31199 [wandb_run.py:_on_init():1763] got version response upgrade_message: "wandb version 0.12.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-04-06 00:26:15,414 INFO    MainThread:31199 [wandb_init.py:init():625] starting run threads in backend
2022-04-06 00:26:16,996 INFO    MainThread:31199 [wandb_run.py:_console_start():1733] atexit reg
2022-04-06 00:26:16,997 INFO    MainThread:31199 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-04-06 00:26:16,998 INFO    MainThread:31199 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-04-06 00:26:16,999 INFO    MainThread:31199 [wandb_run.py:_redirect():1667] Redirects installed.
2022-04-06 00:26:16,999 INFO    MainThread:31199 [wandb_init.py:init():664] run started, returning control to user process
2022-04-06 00:26:17,007 INFO    MainThread:31199 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-06 00:26:17,007 INFO    MainThread:31199 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-06 00:26:17,040 INFO    MainThread:31199 [wandb_init.py:_resume_backend():327] resuming backend
2022-04-06 00:52:10,768 INFO    MainThread:31199 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-06 00:52:10,768 INFO    MainThread:31199 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-06 00:53:20,854 INFO    MainThread:31199 [wandb_init.py:_resume_backend():327] resuming backend
2022-04-06 00:53:21,621 INFO    MainThread:31199 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-06 00:53:21,621 INFO    MainThread:31199 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-06 00:55:00,069 INFO    MainThread:31199 [wandb_init.py:_resume_backend():327] resuming backend
2022-04-06 00:55:00,125 INFO    MainThread:31199 [wandb_init.py:_pause_backend():318] pausing backend
2022-04-06 00:55:00,126 INFO    MainThread:31199 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-04-06 00:55:37,049 INFO    MainThread:31199 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-04-06 00:55:37,051 INFO    MainThread:31199 [wandb_run.py:_restore():1674] restore
